# ================ 开发环境配置 ================

# 日志级别配置
logging:
  level:
    root: info
    web: debug

# 数据库配置
datasource:
  host: 127.0.0.1
  port: 3306
  database: springboot_example
  username: root
  password: hujinbo
